// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModelAPI.Context;

#nullable disable

namespace ModelAPI.Migrations
{
    [DbContext(typeof(AeroportoContext))]
    [Migration("20241204210717_CriacaoTabelaControleDeTrafego")]
    partial class CriacaoTabelaControleDeTrafego
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ModelAPI.Entities.ControleDeTrafego", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("ControleDeTrafegos");
                });

            modelBuilder.Entity("ModelAPI.Entities.Voo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ControleDeTrafegoId")
                        .HasColumnType("int");

                    b.Property<string>("Destino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ControleDeTrafegoId");

                    b.ToTable("Voo");
                });

            modelBuilder.Entity("ModelAPI.Entities.Voo", b =>
                {
                    b.HasOne("ModelAPI.Entities.ControleDeTrafego", null)
                        .WithMany("Voo_ativos")
                        .HasForeignKey("ControleDeTrafegoId");
                });

            modelBuilder.Entity("ModelAPI.Entities.ControleDeTrafego", b =>
                {
                    b.Navigation("Voo_ativos");
                });
#pragma warning restore 612, 618
        }
    }
}
